server:
  port: 9998

spring:
  resources:
    static-locations=classpath:/static/:
  mvc:
    static-path-pattern=/static/**:
  datasource:
    url: jdbc:mysql://localhost:3306/WuGong
    username: root
    password: lwy0328
    driver-class-name: com.mysql.cj.jdbc.Driver
