server:
  port: 9998

spring:
  mvc:
    static-path-pattern=/**:
  datasource:
    url: jdbc:mysql://localhost:3306/WuGong
    username: root
    password: lwy0328
    driver-class-name: com.mysql.cj.jdbc.Driver

